version: '3.8'
  
services:
  redis:
    image: docker.io/bitnami/redis:7.0
    networks:
      - sentry-kong
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  kong:
    build:
      dockerfile: Containerfile
    environment:
      KONG_LOG_LEVEL: info
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_STATUS_LISTEN: "0.0.0.0:8100"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    healthcheck:
        interval: 10s
        timeout: 3s
        start_period: 1s
        test: ["CMD-SHELL", "nc -z -v localhost 8000"]
    ports:
      - "9000:8000"
      - "9433:8433"
      - "9001:8001"
      - "9100:8100"
    restart: unless-stopped
    networks:
      - sentry-kong
    depends_on:
      - redis

networks:
  sentry-kong:
    name: "sentry-kong"